/**
 * Regenerates the demo catalog section of README.md from the source tree.
 *
 *   npx ts-node tools/readme.ts           # rewrite the section in place
 *   npx ts-node tools/readme.ts --check   # exit 1 if README is out of date (CI)
 *
 * The section lives between the markers below; everything else in the
 * README is hand-written and left untouched.
 */
import * as fs from "node:fs";
import * as path from "node:path";
import { type Demo, ROOT, envUsage, loadCatalog } from "./catalog";
import { green, red } from "./ui";

const README = path.join(ROOT, "README.md");
const START = "<!-- catalog:start -->";
const END = "<!-- catalog:end -->";

function escapeCell(s: string): string {
  return s.replace(/\|/g, "\\|");
}

export function renderCatalog(demos: Demo[]): string {
  const lines: string[] = [START, "", "_Generated by `npm run catalog`. Do not edit by hand._", ""];
  let net = "";
  for (const d of demos) {
    if (d.network.dir !== net) {
      net = d.network.dir;
      const chain = d.network.chainId ? ` (chain id ${d.network.chainId})` : "";
      const warn = d.network.mainnet ? " ⚠️ real funds" : "";
      lines.push(
        `#### ${d.network.label}${chain}${warn}`,
        "",
        "| Demo | What it does | Env vars |",
        "|---|---|---|",
      );
    }
    const wip = d.wip ? " _(WIP)_" : "";
    lines.push(
      `| [\`${d.id}\`](${d.file})${wip} | ${escapeCell(d.description)} | ${d.env.map((v) => `\`${v}\``).join(" ") || "none"} |`,
    );
    const next = demos[demos.indexOf(d) + 1];
    if (!next || next.network.dir !== net) lines.push("");
  }
  const usage = envUsage(demos);
  lines.push("#### Environment variables", "", "| Variable | Used by |", "|---|---|");
  for (const [name, ids] of usage)
    lines.push(`| \`${name}\` | ${ids.length} demo${ids.length === 1 ? "" : "s"} |`);
  lines.push("", END);
  return lines.join("\n");
}

function splice(readme: string, section: string): string {
  const a = readme.indexOf(START);
  const b = readme.indexOf(END);
  if (a === -1 || b === -1 || b < a) {
    throw new Error(`README.md must contain the markers ${START} and ${END}`);
  }
  return readme.slice(0, a) + section + readme.slice(b + END.length);
}

if (require.main === module) {
  const current = fs.readFileSync(README, "utf8");
  const next = splice(current, renderCatalog(loadCatalog()));
  if (process.argv.includes("--check")) {
    if (next !== current) {
      console.error(red("README.md catalog is out of date. Run: npm run catalog"));
      process.exit(1);
    }
    console.log(green("README.md catalog is up to date."));
  } else if (next !== current) {
    fs.writeFileSync(README, next);
    console.log(green("README.md catalog updated."));
  } else {
    console.log("README.md catalog already up to date.");
  }
}
